### ISSUE TITLE
Script error on marking as (un)watched

### ISSUE THREAD

**Issue by matejdro** [hippojay/plugin.video.plexbmc#108]
When I try to mark episode as watched or as unwatched, I will get following error:

```
16:31:08 T:4112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('None',)
                                            Traceback (most recent call last):
                                              File "C:\Users\Matej\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-4.0.0beta4\default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "C:\Users\Matej\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-4.0.0beta4\resources\lib\plexbmc.py", line 4142, in start_plexbmc
                                                watched(server_uuid, metadata_id, watch_status )
                                              File "C:\Users\Matej\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-4.0.0beta4\resources\lib\plexbmc.py", line 3711, in watched
                                                server=plex_network.get_server_from_uuid(server_uuid)
                                              File "C:\Users\Matej\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-4.0.0beta4\resources\lib\plex.py", line 514, in get_server_from_uuid
                                                return self.server_list[uuid]
                                            KeyError: ('None',)
                                            -->End of Python script error report<--
```

Running Plexbmc 4.0.0 beta4, Plex 0.9.12.3.1173-937aac3. Otherwise browsing and playing episodes seems to work fine.

**Comment by sigmaxt** [comment]
Having same problem. Wish i has some help to provide. Searching for a solution. If I find anything will post back.

Log file shows same as above post.
Plex V0.9.12.11
Plexbmc v4.0.0 beta4 
Kodi V15.1.0.0
