### ISSUE TITLE
Python script returns error after starting plexbmc

### ISSUE THREAD

**Issue by 0x24D** [hippojay/plugin.video.plexbmc#121]
Whenever I start the plexbmc plugin to find a remote server I receive an error. 

The following is part of the log file that contains the error, after I start the plugin.

```
15:00:20 T:140160239724288  NOTICE: ===== PLEXBMC START =====
15:00:20 T:140160239724288  NOTICE: PleXBMC -> Running Python: sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0)
15:00:20 T:140160239724288  NOTICE: PleXBMC -> Running PleXBMC: 3.4.5
15:00:20 T:140160239724288  NOTICE: PleXBMC -> FullRes Thumbs are se to: false
15:00:20 T:140160239724288  NOTICE: PleXBMC -> CWD is set to: /home/daniel/.kodi/addons/plugin.video.plexbmc-3.4.5
15:00:20 T:140160239724288  NOTICE: PleXBMC -> Platform: Linux/RPi
15:00:20 T:140160239724288  NOTICE: PleXBMC -> Debug is turned off.  Running silent
15:00:20 T:140160239724288  NOTICE: PleXBMC -> Detected parameters: {'content_type': 'video'}
15:00:20 T:140160239724288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'details' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/daniel/.kodi/addons/plugin.video.plexbmc-3.4.5/default.py", line 5306, in <module>
                                                displaySections()
                                              File "/home/daniel/.kodi/addons/plugin.video.plexbmc-3.4.5/default.py", line 1291, in displaySections
                                                details['title']="Refresh Data"
                                            UnboundLocalError: local variable 'details' referenced before assignment
                                            -->End of Python script error report<--
15:00:20 T:140160239724288    INFO: Python script stopped
```

**Comment by Rockycjc** [comment]
I noticed you are using 3.4.5.  Have you tried using the latest version of the plugin (4 beta)?

**Comment by 0x24D** [comment]
@Rockycjc I have just tried it and I can find the server but I receive an error when I try to log in.

Here is the log:
````
19:45:06 T:139968932464384  NOTICE: ===== PLEXBMC START [id: 1440009906.23] =====
19:45:06 T:139968932464384  NOTICE: PleXBMC -> Reading settings configuration
19:45:07 T:139968932464384   ERROR: /usr/lib/python2.7/dist-packages/cffi/vengine_cpy.py:177: UserWarning: reimporting '_Cryptography_cffi_a269d620xd5c405b7' might overwrite older definitions
                                              % (self.verifier.get_module_name()))
19:45:07 T:139968932464384  NOTICE: PleXBMC -> Running PleXBMC: 4.0.0~beta4
19:45:07 T:139968932464384  NOTICE: PleXBMC -> Script argument is ['default.py', 'signin']
19:45:07 T:139968932464384  NOTICE: PleXBMC -> Running Python: sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0)
19:45:07 T:139968932464384  NOTICE: PleXBMC -> CWD is set to: /home/daniel/.kodi/addons/plugin.video.plexbmc-helix
19:45:07 T:139968932464384  NOTICE: PleXBMC -> Platform: Linux/RPi
19:45:07 T:139968932464384  NOTICE: PleXBMC -> Setting debug: info
19:45:07 T:139968932464384  NOTICE: PleXBMC -> FullRes Thumbs are set to: False
19:45:07 T:139968932464384  NOTICE: PleXBMC -> Settings streaming: 1
19:45:07 T:139968932464384  NOTICE: PleXBMC -> Setting filter menus: True
19:45:07 T:139968932464384  NOTICE: PleXBMC -> Flatten is: 0
19:45:07 T:139968932464384  NOTICE: PleXBMC -> Setting stream Control to : PLEX CONTROL
19:45:07 T:139968932464384  NOTICE: PleXBMC -> Force DVD playback: False
19:45:07 T:139968932464384  NOTICE: PleXBMC -> SMB IP Override: False
19:45:07 T:139968932464384  NOTICE: setting: nasoverrideip is :
19:45:07 T:139968932464384  NOTICE: PleXBMC -> NAS IP:
19:45:07 T:139969787713280  NOTICE: PleXBMC.plex -> talk_to_myplex : url = https://plex.tv/users/account
19:45:08 T:139968932464384  NOTICE: PleXBMC.plex -> talk_to_myplex : url = https://plex.tv/pins.xml
19:45:08 T:139969787713280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: initializer for ctype 'int(*)(int, X509_STORE_CTX *)' must be a pointer to same type, not cdata 'int(*)(int, X509_STORE_CTX *)'
                                            Traceback (most recent call last):
                                              File "/home/daniel/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/home/daniel/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plexbmc.py", line 4105, in start_plexbmc
                                                manage_window.start()
                                              File "/home/daniel/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plex_signin.py", line 242, in start
                                                self.gather_plex_information()
                                              File "/home/daniel/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plex_signin.py", line 247, in gather_plex_information
                                                user = self.plex_network.get_myplex_information()
                                              File "/home/daniel/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plex.py", line 610, in get_myplex_information
                                                data = self.talk_to_myplex('/users/account')
                                              File "/home/daniel/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plex.py", line 397, in talk_to_myplex
                                                response = requests.get("%s%s" % (self.myplex_server, path), params=self.plex_identification(), verify=True, timeout=(3,10))
                                              File "/home/daniel/.kodi/addons/script.module.requests/lib/requests/api.py", line 69, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/daniel/.kodi/addons/script.module.requests/lib/requests/api.py", line 50, in request
                                                response = session.request(method=method, url=url, **kwargs)
                                              File "/home/daniel/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 465, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/home/daniel/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 573, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/daniel/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 370, in send
                                                timeout=timeout
                                              File "/home/daniel/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
                                                body=body, headers=headers)
                                              File "/home/daniel/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
                                                self._validate_conn(conn)
                                              File "/home/daniel/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
                                                conn.connect()
                                              File "/home/daniel/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connection.py", line 238, in connect
                                                ssl_version=resolved_ssl_version)
                                              File "/home/daniel/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 262, in ssl_wrap_socket
                                                ctx.set_verify(_openssl_verify[cert_reqs], _verify_callback)
                                              File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 753, in set_verify
                                                _lib.SSL_CTX_set_verify(self._context, mode, self._verify_callback)
                                            TypeError: initializer for ctype 'int(*)(int, X509_STORE_CTX *)' must be a pointer to same type, not cdata 'int(*)(int, X509_STORE_CTX *)'
                                            -->End of Python script error report<--
````

**Comment by Rockycjc** [comment]
Well.  That was all I had.  Going to have to wait fir hippojay to look at it.  He said he won't be able to come back and look at the bugs until the end of the month.

**Comment by jun6lee** [comment]
I'm not even getting that far, idiotically I updated one too many things at once, so I'm unsure what change has broken this.

Previous setup:
OSX Mavericks // Kodi Gotham // Skin: Nebula

New setup:
OSX EL Capitano // Kodi Isengard // Skin: Nebula

22:17:31 T:123145316409344  NOTICE: ===== PLEXBMC START =====
22:17:31 T:123145318019072  NOTICE: -->Python Interpreter Initialized<--
22:17:31 T:123145316409344  NOTICE: Previous line repeats 1 times.
22:17:31 T:123145316409344  NOTICE: PleXBMC -> Reading settings configuration
22:17:31 T:123145316409344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named requests
                                            Traceback (most recent call last):
                                              File "/Users/j44nw4r/Library/Application Support/Kodi/addons/plugin.video.plexbmc-3.6.1/default.py", line 11, in <module>
                                                import plexbmc
                                              File "/Users/j44nw4r/Library/Application Support/Kodi/addons/plugin.video.plexbmc-3.6.1/resources/lib/plexbmc.py", line 43, in <module>
                                                import plex
                                              File "/Users/j44nw4r/Library/Application Support/Kodi/addons/plugin.video.plexbmc-3.6.1/resources/lib/plex.py", line 9, in <module>
                                                import requests
                                            ImportError: No module named requests
                                            -->End of Python script error report<--

Tried Upgrading Plexbmc to latest 4.0.0 Beta, no luck there: 

22:20:59 T:123145321238528  NOTICE: -->Python Interpreter Initialized<--
22:20:59 T:123145321238528  NOTICE: ===== PLEXBMC START [id: 1444755059.17] =====
22:20:59 T:123145323384832  NOTICE: Thread JobWorker start, auto delete: true
22:20:59 T:123145323462656  NOTICE: Thread RSSReader start, auto delete: false
22:20:59 T:123145321238528  NOTICE: PleXBMC -> Reading settings configuration
22:20:59 T:123145321775104  NOTICE: -->Python Interpreter Initialized<--
22:20:59 T:123145321238528  NOTICE: Previous line repeats 1 times.
22:20:59 T:123145321238528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named requests
                                            Traceback (most recent call last):
                                              File "/Users/j44nw4r/Library/Application Support/Kodi/addons/plugin.video.plexbmc-4.0.0beta4/default.py", line 11, in <module>
                                                import plexbmc
                                              File "/Users/j44nw4r/Library/Application Support/Kodi/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexbmc.py", line 42, in <module>
                                                import plex
                                              File "/Users/j44nw4r/Library/Application Support/Kodi/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plex.py", line 9, in <module>
                                                import requests
                                            ImportError: No module named requests
                                            -->End of Python script error report<--

**Comment by hippojay** [comment]
How are you updating?  If you are just copying the files from GitHub, then the dependencies won't be installed. Plexbmc uses the kodi module for requests, which should be installed when plexbmc is installed - but only if you install it through kodi.

**Comment by nicheplayer** [comment]
I seem to have a similar error running the latest plexbmc isengard branch on Kodi 15.2 running on a FireTV:

`00:00:32 T:1679379240  NOTICE: ===== PLEXBMC START [id: 1449208832.01] =====
00:00:32 T:1679379240  NOTICE: PleXBMC -> Reading settings configuration
00:00:33 T:1679379240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'declare_namespace'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-Isengard/default.py", line 8, in <module>
                                                from resources.lib import plexbmc
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-Isengard/resources/lib/plexbmc.py", line 41, in <module>
                                                from resources.lib.plex import plex
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-Isengard/resources/lib/plex/plex.py", line 9, in <module>
                                                import requests
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 53, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 48, in <module>
                                                from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-Isengard/resources/lib/ndg/__init__.py", line 19, in <module>
                                                __import__('pkg_resources').declare_namespace(__name__)
                                            AttributeError: 'module' object has no attribute 'declare_namespace'
                                            -->End of Python script error report<--`

**Comment by wootts** [comment]
Does anyone have an update on this i'm getting the same fault. love this addon be a shame not to be able to use it

**Comment by arqamovais** [comment]
I was having the same error on kodi 15.2 with the PleXBMC 3.4.5 on fire tv stick so i updated it to the latest from here, but to no avail same error. I then reinstalled 3.4.5 but restarted my Plex server several times, tried it again and PleXBMC opened and started working. It maybe a fluke but just to let anyone know having the same issue

**Comment by ducktalesAWWOOOWOO** [comment]
Hi

Love this plugin.  

Was working fine, the upgraded to Isenguard in process of wiping my Fire stick as i had overloaded it a bit, then found my way on to 4.1.0.  Getting same error from what I can see.

/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-Isengard/default.py): instantiating addon using automatically obtained id of "plugin.video.plexbmc" dependent on version 2.20.0 of the xbmc.python api
22:15:55 T:1542290368  NOTICE: ===== PLEXBMC START [id: 1450563355.5] =====
22:15:55 T:1086564320   DEBUG: ------ Window Init (DialogBusy.xml) ------
22:15:55 T:1542290368  NOTICE: PleXBMC -> Reading settings configuration
22:15:56 T:1542290368   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'declare_namespace'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-Isengard/default.py", line 8, in <module>
                                                from resources.lib import plexbmc
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-Isengard/resources/lib/plexbmc.py", line 41, in <module>
                                                from resources.lib.plex import plex
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-Isengard/resources/lib/plex/plex.py", line 9, in <module>
                                                import requests
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 53, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 48, in <module>
                                                from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-Isengard/resources/lib/ndg/__init__.py", line 19, in <module>
                                                __import__('pkg_resources').declare_namespace(__name__)
                                            AttributeError: 'module' object has no attribute 'declare_namespace'
                                            -->End of Python script error report<--
22:15:56 T:1086564320   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
22:15:56 T:1542290368    INFO: Python script stopped
22:15:56 T:1542290368   DEBUG: Thread LanguageInvoker 1542290368 terminating
22:15:56 T:1541279352   DEBUG:  bool XFILE::CPluginDirectory::WaitOnScriptResult(const string&, int, const string&, bool) - plugin exited prematurely - terminating
22:15:56 T:1086564320   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.plexbmc/?content_type=video
22:15:56 T:1086564320   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexbmc/?content_type=video) failed
22:15:56 T:1086564320   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/video)
22:15:56 T:1086564320   DEBUG:   ParentPath = [addons://sources/]
22:15:56 T:1530119360  NOTICE: Thread BackgroundLoader start, auto delete: false
22:15:56 T:1530119360   DEBUG: Thread BackgroundLoader 1530119360 terminating
22:15:56 T:1086564320   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
22:16:01 T:1086564320   DEBUG: ------ Window Deinit (DialogKaiToast.xml) ------

Install process.

Side load ADBFire of Kodi Isenguard onto Fire TV stick.
Side load 4.1.0 zip on to Fire TV stick
Installed via Kodi.

Any fix appreciated @hippojay !

Merry Christmas

**Comment by paulmaidmentuk** [comment]
@hippojay

I also +1 this. I am running an ARM build of isengard with the latest version of the plugin. Very similar errors.

Is this somehow related to the python version that is bundled with Isengard for Android/ARM?

**Comment by apetherick** [comment]
+1:

`13:33:07 64278.832031 T:2615145392 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-fanart.png
13:33:07 64278.835938 T:2615145392 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/fanart.png
13:33:19 64290.851562 T:2682254256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'details' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/xbian/.kodi/addons/plugin.video.plexbmc-3.4.5/default.py", line 5306, in <module>
                                                displaySections()
                                              File "/home/xbian/.kodi/addons/plugin.video.plexbmc-3.4.5/default.py", line 1291, in displaySections
                                                details['title']="Refresh Data"
                                            UnboundLocalError: local variable 'details' referenced before assignment
                                            -->End of Python script error report<--
13:33:19 64291.066406 T:3020165120   ERROR: GetDirectory - Error getting plugin://plugin.video.plexbmc/?content_type=video
13:33:19 64291.074219 T:3020165120   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexbmc/?content_type=video) failed
13:33:19 64291.242188 T:2682254256 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-poster.jpg
13:33:19 64291.242188 T:2682254256 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-poster.png
13:33:19 64291.246094 T:2682254256 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-banner.jpg
13:33:19 64291.250000 T:2682254256 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-banner.png
13:33:19 64291.253906 T:2682254256 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-fanart.jpg
13:33:19 64291.253906 T:2682254256 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/fanart.jpg
13:33:19 64291.257812 T:2682254256 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-fanart.png
13:33:19 64291.257812 T:2682254256 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/fanart.png
`
