### ISSUE TITLE
osrandom engin already registered error.

### ISSUE THREAD

**Issue by aktur** [hippojay/plugin.video.plexbmc#123]
When I try to start latest beta4 Plexbmc I get the following runtime error (running it on RP2):

16:23:15 T:1781527568  NOTICE: ===== PLEXBMC START [id: 1441030995.23] =====
16:23:15 T:1781527568  NOTICE: PleXBMC -> Reading settings configuration
16:23:16 T:1781527568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: osrandom engine already registered
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.plexbmc-4.0.0beta4/default.py", line 11, in <module>
                                                import plexbmc
                                              File "/home/pi/.kodi/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexbmc.py", line 42, in <module>
                                                import plex
                                              File "/home/pi/.kodi/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plex.py", line 9, in <module>
                                                import requests
                                              File "/home/pi/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 53, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/home/pi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 53, in <module>
                                                import OpenSSL.SSL
                                              File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
                                                from OpenSSL import rand, crypto, SSL
                                              File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
                                                from OpenSSL._util import (
                                              File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 7, in <module>
                                                binding = Binding()
                                              File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 63, in __init__
                                                self._ensure_ffi_initialized()
                                              File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 95, in _ensure_ffi_initialized
                                                cls._register_osrandom_engine()
                                              File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 70, in _register_osrandom_engine
                                                raise RuntimeError("osrandom engine already registered")
                                            RuntimeError: osrandom engine already registered
                                            -->End of Python script error report<--

**Comment by Larnal** [comment]
Same errors here with Emby for Kodi, Trakt.tv and Trakt.tv for Pulsar addons. All the info are in this thread : 
http://emby.media/community/index.php?/topic/25735-emby-for-kodi-broken-no-sync/

**Comment by hippojay** [comment]
Thanks for the report - it seems to be a requests and configuration issue and nothing I can do to influence it.  I'm thinking of bring requests into the addon, so remove the dependency on the version from kodi - so this might give more control.  As of now, i'll close this - but will keep it in mind.

**Comment by hippojay** [comment]
Lol.  just ran into this myself now.  Seems to be an issue withthe python 2.7 cryptograph module, which is used by requests when brining in the SSL modules.

Looks like it's fixed in cryptography 1.1 - although this is slightly difficult to get on the Wily build (but would appear to be default afterwards).  Best bet is to just rename the dir:

# sudo mv /usr/lib/python2.7/dist-packages/cryptography /usr/lib/python2.7/dist-packages/cryptography.old

**Comment by aktur** [comment]
This fix does not work for me:

pi@raspberrypi ~ $ ls -l /usr/lib/python2.7/dist-packages/cryptography
ls: cannot access /usr/lib/python2.7/dist-packages/cryptography: No such file or directory

**Comment by cvwordragen** [comment]
the solution suggested by hippojay worked for me
it is not an ellegant solution, but is works
had the same problem with the Zen addon in Kodi
move /usr/lib/python2.7/dist-packages/cryptography to /usr/lib/python2.7/dist-packages/cryptography.old
