### ISSUE TITLE
AttributeError: 'module' object has no attribute 'declare_namespace'cant connect

### ISSUE THREAD

**Issue by wurtzelsepp** [hippojay/plugin.video.plexbmc#149]
Hi i am using a firetv and cant now connect to my plex server. 

Here My logFile:

19:26:49 T:1583120840  NOTICE: special://profile/ is mapped to: special://masterprofile/
19:26:49 T:1583120840  NOTICE: -----------------------------------------------------------------------
19:26:49 T:1583120840  NOTICE: Starting Kodi (15.2 Git:2015-10-19-02e7013). Platform: Android ARM 32-bit
19:26:49 T:1583120840  NOTICE: Using Release Kodi x32 build
19:26:49 T:1583120840  NOTICE: Kodi compiled Oct 19 2015 by GCC 4.8.0 for Android ARM 32-bit API level 17 (API level 17)
19:26:49 T:1583120840  NOTICE: Running on Amazon AFTB with Android 4.2.2 API level 17, kernel: Linux ARM 32-bit version 3.4.0-perf-gc05e844-00001-gd574c65
19:26:49 T:1583120840  NOTICE: FFmpeg version: 2.6.4-kodi-2.6.4-Isengard
19:26:49 T:1583120840  NOTICE: Host CPU: ARMv7 Processor rev 0 (v7l), 4 cores available
19:26:49 T:1583120840  NOTICE: Product: bueller, Device: bueller, Board: MSM8960 - Manufacturer: Amazon, Brand: qcom, Model: AFTB, Hardware: qcom
19:26:49 T:1583120840  NOTICE: External storage path = /storage/emulated/0; status = ok
19:26:49 T:1583120840  NOTICE: ARM Features: Neon enabled
19:26:49 T:1583120840  NOTICE: special://xbmc/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
19:26:49 T:1583120840  NOTICE: special://xbmcbin/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
19:26:49 T:1583120840  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
19:26:49 T:1583120840  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
19:26:49 T:1583120840  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
19:26:49 T:1583120840  NOTICE: The executable running is:
19:26:49 T:1583120840  NOTICE: Local hostname: localhost
19:26:49 T:1583120840  NOTICE: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
19:26:49 T:1583120840  NOTICE: -----------------------------------------------------------------------
19:26:49 T:1583120840  NOTICE: load settings...
19:26:49 T:1583120840   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
19:26:49 T:1583120840 WARNING: CSettingInt: unknown options filler "audiocdactions" of "audiocds.autoaction"
19:26:49 T:1583120840   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
19:26:49 T:1583120840   DEBUG: AESinkAUDIOTRACK - 44100 supported
19:26:49 T:1583120840   DEBUG: AESinkAUDIOTRACK - 48000 supported
19:26:49 T:1583120840  NOTICE: Found 1 Lists of Devices
19:26:49 T:1583120840  NOTICE: Enumerated AUDIOTRACK devices:
19:26:49 T:1583120840  NOTICE:     Device 1
19:26:49 T:1583120840  NOTICE:         m_deviceName      : AudioTrack
19:26:49 T:1583120840  NOTICE:         m_displayName     : android
19:26:49 T:1583120840  NOTICE:         m_displayNameExtra: audiotrack
19:26:49 T:1583120840  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
19:26:49 T:1583120840  NOTICE:         m_channels        : FL,FR,FC,LFE,BL,BR
19:26:49 T:1583120840  NOTICE:         m_sampleRates     : 44100,48000
19:26:49 T:1583120840  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_AC3,AE_FMT_DTS
19:26:49 T:1583120840   ERROR: CSettings: unable to load settings from special://masterprofile/guisettings.xml, creating new default settings
19:26:49 T:1583120840  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
19:26:49 T:1583120840  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
19:26:49 T:1583120840  NOTICE: Default DVD Player: dvdplayer
19:26:49 T:1583120840  NOTICE: Default Video Player: dvdplayer
19:26:49 T:1583120840  NOTICE: Default Audio Player: paplayer
19:26:49 T:1583120840  NOTICE: Disabled debug logging due to GUI setting. Level 0.
19:26:49 T:1583120840  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
19:26:49 T:1583120840  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
19:26:49 T:1583120840  NOTICE: Loaded playercorefactory configuration
19:26:49 T:1583120840  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
19:26:49 T:1583120840  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
19:26:49 T:1550404624  NOTICE: Thread ActiveAE start, auto delete: false
19:26:49 T:1540975432  NOTICE: Thread AESink start, auto delete: false
19:26:49 T:1583120840  NOTICE: Running database version Addons19
19:26:49 T:1583120840  NOTICE: ADDONS: Using repository repository.xbmc.org
19:26:49 T:1583120840  NOTICE: ADDONS: Using repository repository.lost-and-found
19:26:49 T:1583120840  NOTICE: virtual bool CWinSystemEGL::InitWindowSystem(): Using EGL Implementation: android
19:26:50 T:1583120840  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
19:26:50 T:1583120840  NOTICE: Previous line repeats 1 times.
19:26:50 T:1583120840  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
19:26:50 T:1583120840  NOTICE: Found (1920x1080@60.000000) at 16, setting to RES_DESKTOP at 16
19:26:50 T:1583120840  NOTICE: Checking resolution 16
19:26:50 T:1583120840  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
19:26:50 T:1583120840  NOTICE: GL_VENDOR = Qualcomm
19:26:50 T:1583120840  NOTICE: GL_RENDERER = Adreno (TM) 320
19:26:50 T:1583120840  NOTICE: GL_VERSION = OpenGL ES 3.0 V@14.0 AU@04.02.02.073.286 (CL@3908834)
19:26:50 T:1583120840  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.00
19:26:50 T:1583120840  NOTICE: GL_EXTENSIONS = GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_labelGL_EXT_debug_markerGL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float
19:26:50 T:1583120840  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
19:26:50 T:1583120840 WARNING: Unable to resolve: /libcec.so CECInitialise, reason: Symbol not found:
19:26:50 T:1583120840   ERROR: Unable to resolve exports from dll libcec.so
19:26:50 T:1583120840   ERROR: virtual void PERIPHERALS::CPeripherals::Initialise() - failed to initialise bus cec
19:26:50 T:1558328480  NOTICE: Thread PeripBusUSB start, auto delete: false
19:26:50 T:1583120840  NOTICE: Running database version Addons19
19:26:50 T:1583120840  NOTICE: Running database version ViewModes6
19:26:50 T:1583120840  NOTICE: Running database version Textures13
19:26:50 T:1583120840  NOTICE: Running database version MyMusic52
19:26:50 T:1583120840  NOTICE: Running database version MyVideos93
19:26:50 T:1583120840  NOTICE: Running database version TV29
19:26:50 T:1583120840  NOTICE: Running database version Epg10
19:26:50 T:1583120840 WARNING: JSONRPC: Could not parse type "PVR.Details.Channel"
19:26:50 T:1583120840 WARNING: JSONRPC: Could not parse type "PVR.Details.ChannelGroup.Extended"
19:26:50 T:1583120840 WARNING: JSONRPC: Could not parse type "GUI.Property.Value"
19:26:50 T:1583120840 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
19:26:50 T:1568810328  NOTICE: Thread LanguageInvoker start, auto delete: false
19:26:50 T:1583120840  NOTICE: initialize done
19:26:50 T:1583120840  NOTICE: Running the application...
19:26:50 T:1569363528  NOTICE: Thread LanguageInvoker start, auto delete: false
19:26:51 T:1571428288  NOTICE: Thread JobWorker start, auto delete: true
19:26:51 T:1568810328  NOTICE: -->Python Interpreter Initialized<--
19:26:51 T:1583120840  NOTICE: Previous line repeats 1 times.
19:26:51 T:1583120840  NOTICE: starting zeroconf publishing
19:26:51 T:1571964992  NOTICE: Thread ZerocconfEmbedded start, auto delete: false
19:26:51 T:1583120840  NOTICE: starting upnp client
19:26:51 T:1575771864  NOTICE: Thread JobWorker start, auto delete: true
19:26:51 T:1583120840  NOTICE: ES: Starting event server
19:26:51 T:1575982384  NOTICE: Thread TCPServer start, auto delete: false
19:26:51 T:1583120840  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
19:26:51 T:1583120840  NOTICE: GL_VENDOR = Qualcomm
19:26:51 T:1583120840  NOTICE: GL_RENDERER = Adreno (TM) 320
19:26:51 T:1583120840  NOTICE: GL_VERSION = OpenGL ES 3.0 V@14.0 AU@04.02.02.073.286 (CL@3908834)
19:26:51 T:1575981720  NOTICE: Thread EventServer start, auto delete: false
19:26:51 T:1583120840  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.00
19:26:51 T:1575981720  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
19:26:51 T:1583120840  NOTICE: GL_EXTENSIONS = GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_labelGL_EXT_debug_markerGL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float
19:26:51 T:1575981720  NOTICE: UDP: Listening on port 9777
19:26:51 T:1576511720  NOTICE: Thread RSSReader start, auto delete: false
19:26:51 T:1569363528  NOTICE: PleXBMC.setting -> Reading settings configuration
19:26:51 T:1569363528  NOTICE: PleXBMC.setting -> Unable to read KODI's guisettings.xml
19:26:52 T:1569363528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'declare_namespace'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/helper.py", line 36, in <module>
                                                from resources.lib.helper.functions import *
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/helper/functions.py", line 11, in <module>
                                                from resources.lib.plex.plex import Plex
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/plex/plex.py", line 9, in <module>
                                                import requests
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/**init**.py", line 53, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
                                                from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/ndg/**init**.py", line 19, in <module>
                                                **import**('pkg_resources').declare_namespace(**name**)
                                            AttributeError: 'module' object has no attribute 'declare_namespace'
                                            -->End of Python script error report<--
19:27:00 T:1576274920  NOTICE: Thread BackgroundLoader start, auto delete: false
19:27:05 T:1581499800  NOTICE: Thread LanguageInvoker start, auto delete: false
19:27:05 T:1581499800  NOTICE: -->Python Interpreter Initialized<--
19:27:05 T:1581499800  NOTICE: ===== PLEXBMC START [id: 1452018425.2] =====
19:27:05 T:1581499800  NOTICE: PleXBMC.setting -> Reading settings configuration
19:27:05 T:1581499800  NOTICE: PleXBMC.setting -> Unable to read KODI's guisettings.xml
19:27:05 T:1581499800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'declare_namespace'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/default.py", line 8, in <module>
                                                from resources.lib import plexbmc
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/plexbmc.py", line 41, in <module>
                                                from resources.lib.plex import plex
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/plex/plex.py", line 9, in <module>
                                                import requests
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/**init**.py", line 53, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
                                                from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/ndg/**init**.py", line 19, in <module>
                                                **import**('pkg_resources').declare_namespace(**name**)
                                            AttributeError: 'module' object has no attribute 'declare_namespace'
                                            -->End of Python script error report<--
19:27:05 T:1583120840   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.plexbmc/?content_type=video
19:27:05 T:1583120840   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexbmc/?content_type=video) failed
19:27:05 T:1575797568  NOTICE: Thread BackgroundLoader start, auto delete: false
19:27:06 T:1575260848  NOTICE: Thread LanguageInvoker start, auto delete: false
19:27:06 T:1575260848  NOTICE: -->Python Interpreter Initialized<--
19:27:06 T:1575260848  NOTICE: ===== PLEXBMC START [id: 1452018427.0] =====
19:27:07 T:1575260848  NOTICE: PleXBMC.setting -> Reading settings configuration
19:27:07 T:1575260848  NOTICE: PleXBMC.setting -> Unable to read KODI's guisettings.xml
19:27:07 T:1575260848   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'declare_namespace'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/default.py", line 8, in <module>
                                                from resources.lib import plexbmc
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/plexbmc.py", line 41, in <module>
                                                from resources.lib.plex import plex
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/plex/plex.py", line 9, in <module>
                                                import requests
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/**init**.py", line 53, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
                                                from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/ndg/**init**.py", line 19, in <module>
                                                **import**('pkg_resources').declare_namespace(**name**)
                                            AttributeError: 'module' object has no attribute 'declare_namespace'
                                            -->End of Python script error report<--
19:27:07 T:1583120840   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.plexbmc/?content_type=video
19:27:07 T:1583120840   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexbmc/?content_type=video) failed
19:27:07 T:1576075448  NOTICE: Thread BackgroundLoader start, auto delete: false
19:27:08 T:1572780928  NOTICE: Thread LanguageInvoker start, auto delete: false
19:27:08 T:1572780928  NOTICE: -->Python Interpreter Initialized<--
19:27:08 T:1572780928  NOTICE: ===== PLEXBMC START [id: 1452018428.65] =====
19:27:08 T:1572780928  NOTICE: PleXBMC.setting -> Reading settings configuration
19:27:08 T:1572780928  NOTICE: PleXBMC.setting -> Unable to read KODI's guisettings.xml
19:27:09 T:1572780928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'declare_namespace'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/default.py", line 8, in <module>
                                                from resources.lib import plexbmc
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/plexbmc.py", line 41, in <module>
                                                from resources.lib.plex import plex
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/plex/plex.py", line 9, in <module>
                                                import requests
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/**init**.py", line 53, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
                                                from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-isengard-helper-merge/resources/lib/ndg/**init**.py", line 19, in <module>
                                                **import**('pkg_resources').declare_namespace(**name**)
                                            AttributeError: 'module' object has no attribute 'declare_namespace'
                                            -->End of Python script error report<--
19:27:09 T:1583120840   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.plexbmc/?content_type=video
19:27:09 T:1583120840   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexbmc/?content_type=video) failed
19:27:09 T:1575943008  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by wurtzelsepp** [comment]
I also reseted the guisetting
and i reinstalled Kodi but nothing woks. 
Using Kodi 15.2 on firetv (latest)
