### ISSUE TITLE
errors in processing myplex xml (queue)

### ISSUE THREAD

**Issue by redlandmover** [hippojay/plugin.video.plexbmc#47]
here's just the plexbmc portion of the logs, but i attached the full output to: http://xbmclogs.com/ptyt74n0z

looks like a simple speeling (har har) mistake in https://github.com/hippojay/plugin.video.plexbmc/blob/helix/resources/lib/plex.py#L97 'fromsting' should be 'fromstring'?? just a guess :P

18:07:48 T:1896976248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'fromsting'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 4413, in <module>
                                                amberskin()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 3348, in amberskin
                                                root = plex_network.get_myplex_queue()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plex.py", line 175, in get_myplex_queue
                                                return self.get_processed_myplex_xml('/pms/playlists/queue/all')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plex.py", line 97, in get_processed_myplex_xml
                                                return etree.fromsting(data)
                                            AttributeError: 'module' object has no attribute 'fromsting'
                                            -->End of Python script error report<--
18:07:48 T:1905195168   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'str' object has no attribute 'get_formatted_url'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 4507, in <module>
                                                TVShows(param_url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 850, in TVShows
                                                'thumb'             : getThumb(show, server) ,
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 2681, in getThumb
                                                return server.get_formatted_url('/photo/:/transcode?url=%s&width=%s&height=%s' % (urllib.quote_plus('http://localhost:32400' + thumbnail), width, height))
                                            AttributeError: 'str' object has no attribute 'get_formatted_url'
                                            -->End of Python script error report<--

**Comment by hippojay** [comment]
I've fixed this - but plexbmc will generate a lot of these type errors "str object has no attribute" as I move from a simply string to an object to represent the plex server.   This old way of doing it is in every single function that talks to plex - so will take a few days as I go through and test each one.

**Comment by redlandmover** [comment]
if we find them, do you want issues based on them? or just let them be?

**Comment by hippojay** [comment]
Just let them be for now. I'll try and get them done tonight. Then you can unleash the issues :-)
