### ISSUE TITLE
Script fails and occasionally causes whole system to freeze permissions error on statsfile

### ISSUE THREAD

**Issue by desean1625** [hippojay/plugin.video.plexbmc#49]
Where is the statsfile? so I can change the permissions.

 EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (13, 'Permission denied', 'statsfile')
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 14, in <module>
                                                cProfile.run('plexbmc.start_plexbmc()', 'statsfile')
                                              File "/usr/lib/python2.7/cProfile.py", line 34, in run
                                                prof.dump_stats(filename)
                                              File "/usr/lib/python2.7/cProfile.py", line 85, in dump_stats
                                                f = open(file, 'wb')
                                            IOError: (13, 'Permission denied', 'statsfile')
                                            -->End of Python script error report<--

**Comment by hippojay** [comment]
Get the most recent version - this was something I left in by mistake when testing, but I removed it in the last couple of updates.
