### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by desean1625** [hippojay/plugin.video.plexbmc#56]
18:00:20 T:2734421024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/home/osmc/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plexbmc.py", line 4089, in start_plexbmc
                                                amberskin()
                                              File "/home/osmc/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plexbmc.py", line 3032, in amberskin
                                                root = plex_network.get_myplex_queue()
                                              File "/home/osmc/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plex.py", line 150, in get_myplex_queue
                                                return self.get_processed_myplex_xml('/pms/playlists/queue/all')
                                              File "/home/osmc/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plex.py", line 90, in get_processed_myplex_xml
                                                data = self.talk_to_myplex (url)
                                              File "/home/osmc/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plex.py", line 201, in talk_to_myplex
                                                response = requests.get("%s%s" % (self.myplex_server, path), params=dict(self.plex_identification(), **self.get_myplex_token(renew)))
                                              File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
                                                return request('get', url, **kwargs)
                                              File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 420, in send
                                                raise SSLError(e, request=request)
                                            SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
                                            -->End of Python script error report<--

**Comment by hippojay** [comment]
I've been unable to reproduce this on a few systems now.   Would suggest it was a local failure or intermittent fault.  If it reoccurs please re/open a ticket.
