### ISSUE TITLE
Script Failed on load

### ISSUE THREAD

**Issue by hutchy1990** [hippojay/plugin.video.plexbmc#65]
I just get the error script failed when I try to load with XBMC Kodi on Rasp pi is this common?

**Comment by hippojay** [comment]
Shouldn't be. Could you post up a log with some details to see if this is something I can fix.

**Comment by hutchy1990** [comment]
So turn on logs and then try run it again and post the log? I am new to XBMC I use to PlexRPI usually just thought I would try a change see whats better :)

**Comment by hippojay** [comment]
yes please.  Enabled debug+ in the plexbmc settings and pass me over the kodi.log file.

**Comment by trummerjo** [comment]
Get an error on the rasperry too. Could be the same problem. The error in the log is:

19:52:30 T:1515189312   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--               
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                     
                                            Error Type: <type 'exceptions.TypeError'>                                                            
                                            Error Contents: cannot concatenate 'str' and 'bool' objects                                          
                                            Traceback (most recent call last):                                                                   
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-3.4.5/default.py", line 5281, in <module>         
                                                setMasterServer()                                                                                
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-3.4.5/default.py", line 5148, in setMasterServer  
                                                servers=getMasterServer(True)                                                                    
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-3.4.5/default.py", line 2582, in getMasterServer  
                                                for serverData in discoverAllServers().values():                                                 
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-3.4.5/default.py", line 319, in discoverAllServers            
                                                das_myplex = getMyPlexServers()                                                                
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-3.4.5/default.py", line 435, in getMyPlexServers
                                                all_servers = getMyPlexURL(url_path)                                                       
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-3.4.5/default.py", line 691, in getMyPlexURL
                                                conn.request("GET", url_path+"?X-Plex-Token="+getMyPlexToken(renew))          
                                            TypeError: cannot concatenate 'str' and 'bool' objects                            
                                            -->End of Python script error report<--

**Comment by trummerjo** [comment]
Sorry my fault.
4.0.0 beta 4 works fine!
