### ISSUE TITLE
Script error with 4.0.0 beta 4 using Kodi 14.2 on AFTV

### ISSUE THREAD

**Issue by truth1970** [hippojay/plugin.video.plexbmc#96]
Hi,
just tried the plexbmc 4.0.0 beta 4, and I am observing a script error now. I am using Kodi 14.2, Amber Skin on a Amazon Fire TV (most recent AFTV Firmware). The error message pops up from time to time, but playback is still working, despite of the error.

In the kodi.log I see this exception being thrown:
23:57:08 T:1714987816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 71: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plexbmc.py", line 4120, in start_plexbmc
                                                amberskin()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plexbmc.py", line 2962, in amberskin
                                                fullShelf (server_list)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plexbmc.py", line 3280, in fullShelf
                                                printDebug.debug(" Building onDeck window title: %s\n    Building onDeck window url: %s\n    Building onDeck window thumb: %s" % (title_name, title_url, title_thumb))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 71: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by hippojay** [comment]
Thanks - it caused by non-ASCII chars (basically non-english text).  I thought I had caught them all, but must have missed one.  I will check and fix.
