### ISSUE TITLE
Exception when trying to play video (transcoded) with 1.5mbps (int != float) / 4.0.0beta4

### ISSUE THREAD

**Issue by seuffert** [hippojay/plugin.video.plexbmc#97]
Transcode bandwith 2mbps works, as well as 720kbps. 1.5mbps gives this error message:
(android/FireTV Stick)

14:25:38 T:1703425392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: '1.5'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc/files/.spmc/addons/plugin.video.plexbmc-4.0.0beta4/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc/files/.spmc/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexbmc.py", line 4213, in start_plexbmc
                                                playLibraryMedia(param_url,force=force, override=play_transcode)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc/files/.spmc/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexbmc.py", line 1136, in playLibraryMedia
                                                session, playurl=server.get_universal_transcode(streams['extra']['path'])
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc/files/.spmc/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexserver.py", line 477, in get_universal_transcode
                                                mVB=int(bitrate.strip().split('Mbps')[0])*1000
                                            ValueError: invalid literal for int() with base 10: '1.5'
                                            -->End of Python script error report<--

**Comment by hippojay** [comment]
Thanks for the report.  I will get this code looked at again and fixed properly.

Note to self: lookup dict

**Comment by shottothedome** [comment]
Came here to open an issue for the exact same thing. 1.5mbit throws an error. Thank you for your hard work
